# Generated by Django 3.1.2 on 2020-11-03 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('start', models.DateField()),
                ('finish', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='qualification',
            field=models.CharField(default=21, max_length=50),
            preserve_default=False,
        ),
    ]
