# Generated by Django 3.1.2 on 2020-11-04 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201104_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('live_link', models.CharField(max_length=50)),
                ('picturez', models.ManyToManyField(to='api.pictures')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
