# Generated by Django 3.1.2 on 2020-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
